# Η συσκευή είναι ρυθμιζόμενος αισθητήρας κίνησης, ελέγχει την σειρήνα (in/out/battery/service) και την πόρτα (door open/close)

# Adoptable Config
substitutions:
  name: "domino-motion"
  friendly_name: "domino-motion"
esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  # TRUE if using same firmware for other devices like this
  name_add_mac_suffix: false
  project:
    name: "HomeConnected.Motion_Sensor_Plus"
    version: "2024.25.4"
esp8266:
  board: d1_mini
logger:
api:
ota:
dashboard_import:
  import_full_config: true
  package_import_url: github://laptopology/Motion-Sensor/motion-sensor.yaml@main
wifi:
  ap:
    ssid: "${name} Config"
    password: "12345678"
captive_portal:

# Components

# PIR Motion sensor
binary_sensor:
  - name: "Motion Sensor"
    device_class: motion
    platform: gpio
    pin:
      number: D1
    filters:
      - delayed_on: !lambda |-
          return id(DELAY_ON).state * 1000;
      - delayed_off: !lambda |-
          return id(DELAY_OFF).state * 1000;

# "ξηρή" επαφή, μαγνητάκι
  - name: "Door Sensor"
    device_class: door
    platform: gpio    
    pin:
      number: D2
      mode: 
        pullup: True
        input: True
    filters: 
      - delayed_on_off: !lambda |-
          return id(DOOR_DELAY).state * 1000;

# LB ένδειξη χαμηλής μπαταρίας, δεν ξέρω τι τάση βγάζει αυτό,
# αν η τάση που βγάζει αυτό είναι 12v τότε πρέπει να πέσει στα 3 (devider?),
# δε νομίζω να είναι "ξηρή επαφή" αλλιώς πρέπει να βάλουμε 2 ρελέ
  - name: "Battery Low" #  or Siren Input lower than 10.5v for some reason
    icon: mdi:car-battery
    platform: gpio
    pin:
      number: D6
      mode:
        input: True
        pullup: True

# ALARM VER η σειρήνα δίνει συναγερμό στο κέντρο λόγο ενεργοποίησης μεγαφώνου από οποιαδήποτε αιτία,
# αν η τάση που βγάζει αυτό είναι 12v τότε πρέπει να πέσει στα 3 (devider?)
  - name: "Alarm OUT"
    platform: gpio
    icon: mdi:bell-badge-outline
    pin:
      number: D5
      mode: 
        input: True
        pullup: True
    
# Dynamic adjustment
number:
  - platform: template
    name: "Delay ON"
    id: DELAY_ON
    min_value: 1
    max_value: 10
    mode: slider
    device_class: duration
    entity_category: config
    unit_of_measurement: s
    icon: mdi:timer
    step: 1
    optimistic: True
    initial_value: 2
    restore_value: True
  - platform: template
    name: "Delay OFF"
    id: DELAY_OFF
    min_value: 1
    max_value: 30
    mode: slider
    device_class: duration
    entity_category: config
    unit_of_measurement: s
    icon: mdi:timer-off
    step: 1
    optimistic: True
    initial_value: 5
    restore_value: True
  - platform: template
    name: "Door Delay"
    id: DOOR_DELAY
    min_value: 1
    max_value: 30
    mode: slider
    device_class: duration
    entity_category: config
    unit_of_measurement: s
    icon: mdi:timer-outline
    step: 1
    optimistic: True
    initial_value: 2
    restore_value: True

switch:
  # χρειαζόμαστε 2 dry-contact relays για να δώσουμε 12v στις εισόδους της σειρήνας ή εναλλακτικά 3.3->12v logic level shifters
  - platform: gpio
    pin:
      number: RX
      inverted: True
    # IN ενεργοποίηση σειρήνας από τον συναγερμό, εμφανίζονται 12v και ηχεί το μεγάφωνο
    name: "Alarm IN"
    icon: mdi:bullhorn-outline
    
  - platform: gpio
    pin:
      number: D7
      inverted: True
    # TC ενεργοποήση κατάστασης συντήρισης για 10 λεπτά όπου πρέπει να ανοίξει το καπάκι
    name: "Service Mode"
    icon: mdi:account-wrench-outline
    restore_mode: ALWAYS_OFF
