# Η συσκευή είναι ρυθμιζόμενος αισθητήρας κίνησης (motion), ελέγχει την σειρήνα (in/out/battery/service/volts) και την πόρτα (door open/close)

# Adoptable Config
substitutions:
  name: "domino-motion"
  friendly_name: "domino-motion"
esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  # TRUE if using same firmware for other devices like this
  name_add_mac_suffix: false
  project:
    name: "HomeConnected.Motion_Sensor_Plus"
    version: "2024.25.4"
esp8266:
  board: d1_mini
logger:
api:
ota:
dashboard_import:
  import_full_config: true
  package_import_url: github://laptopology/Motion-Sensor/motion-sensor.yaml@main
wifi:
  ap:
    ssid: "${name} Config"
    password: "12345678"
captive_portal:

# Components

# PIR Motion sensor (internal)
binary_sensor:
  - name: "Motion Sensor"
    platform: gpio
    pin:
      number: D1
    device_class: motion
    filters:
      - delayed_on: !lambda |-
          return id(DELAY_ON).state * 1000;
      - delayed_off: !lambda |-
          return id(DELAY_OFF).state * 1000;

# "ξηρή" επαφή, μαγνητάκι
  - name: "Door Sensor"
    platform: gpio
    pin:
      number: D2
      #inverted: true
      mode: 
        pullup: True
        input: True
    device_class: door
    filters: 
      - delayed_on_off: !lambda |-
          return id(DOOR_DELAY).state * 1000;

# LB ένδειξη χαμηλής μπαταρίας or Input lower than 10.5v
  - name: "Battery Low"
    icon: mdi:car-battery
    platform: gpio
    pin:
      number: D6
      mode: 
        pullup: True
        input: True
      inverted: True

# ALARM VER η σειρήνα δίνει συναγερμό στο κέντρο λόγο ενεργοποίησης μεγαφώνου από (εσωτερική) οποιαδήποτε αιτία
  - name: "Alarm OUT"
    icon: mdi:bell-badge-outline
    platform: gpio
    pin:
      number: D5
      mode: 
        pullup: True
        input: True
      inverted: True
switch:
  # το κέντρο δίνει συναγερμό ...IN ενεργοποίηση σειρήνας από τον συναγερμό, εμφανίζονται 12v και ηχεί το μεγάφωνο
  - name: "Alarm IN"
    icon: mdi:bullhorn-outline
    platform: gpio
    pin:
      number: RX
      inverted: True
    
# TC ενεργοποήση κατάστασης συντήρισης για 10 λεπτά όπου πρέπει να ανοίξει το καπάκι να αλλαχθεί η μπαταρία και να κλείσει, μετά reset
  - name: "Service Mode"
    icon: mdi:account-wrench-outline
    platform: gpio
    pin:
      number: D7
      inverted: True

sensor:
  - name: "Battery Voltage"
    platform: adc
    pin: A0
    update_interval: 60s
    filters:
      - calibrate_linear:
         - 0.0 -> 0.0
         - 0.81 -> 12.74

# Dynamic adjustment of motion and door delay
number:
  - platform: template
    name: "Delay ON"
    id: DELAY_ON
    min_value: 1
    max_value: 10
    mode: slider
    device_class: duration
    entity_category: config
    unit_of_measurement: s
    icon: mdi:timer
    step: 1
    optimistic: True
    initial_value: 2
    restore_value: True
  - platform: template
    name: "Delay OFF"
    id: DELAY_OFF
    min_value: 1
    max_value: 30
    mode: slider
    device_class: duration
    entity_category: config
    unit_of_measurement: s
    icon: mdi:timer-off
    step: 1
    optimistic: True
    initial_value: 5
    restore_value: True
  - platform: template
    name: "Door Delay"
    id: DOOR_DELAY
    min_value: 1
    max_value: 30
    mode: slider
    device_class: duration
    entity_category: config
    unit_of_measurement: s
    icon: mdi:timer-outline
    step: 1
    optimistic: True
    initial_value: 2
    restore_value: True
