# Η συσκευή είναι ρυθμιζόμενος αισθητήρας κίνησης, ελέγχει την σειρήνα (in/out/battery/service) και την πόρτα (door open/close)

# Adoptable Config
substitutions:
  name: "domino-motion"
  friendly_name: "domino-motion"
esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  # TRUE if using same firmware for other devices like this
  name_add_mac_suffix: false
  project:
    name: "HomeConnected.Motion_Sensor_Plus"
    version: "2024.25.4"
esp8266:
  board: d1_mini
logger:
api:
ota:
dashboard_import:
  import_full_config: true
  package_import_url: github://laptopology/Motion-Sensor/motion-sensor.yaml@main
wifi:
  ap:
    ssid: "${name} Config"
    password: "12345678"
captive_portal:

# Components
# PIR Motion sensor
binary_sensor:
  - platform: gpio
    pin: D1
    name: "Motion Sensor"
    device_class: motion
    filters:
      - delayed_on: !lambda |-
          return id(DELAY_ON).state;
      - delayed_off: !lambda |-
          return id(DELAY_OFF).state;
  - platform: gpio
    pin: D2
    # "ξηρή" επαφή, μαγνητάκι
    name: "Door Sensor"
    device_class: door
  - platform: gpio
    pin: D6 # GPIO12
    # LB ένδειξη χαμηλής μπαταρίας, δεν ξέρω τι τάση βγάζει αυτό, αν η τάση που βγάζει αυτό είναι 12v τότε πρέπει να πέσει στα 3 (devider?), δε νομίζω να είναι "ξηρή επαφή" αλλιώς πρέπει να βάλουμε 2 ρελέ
    name: "Battery Low" #  or Input lower than 10.5v
  - platform: gpio
    pin: D5 # GPIO12
    # ALARM VER η σειρήνα δίνει συναγερμό στο κέντρο λόγο ενεργοποίησης μεγαφώνου από οποιαδήποτε αιτία, αν η τάση που βγάζει αυτό είναι 12v τότε πρέπει να πέσει στα 3 (devider?)
    name: "Alarm OUT"

# Dynamic adjustment
number:
  - platform: template
    name: "Delay ON"
    id: DELAY_ON
    min_value: 1
    max_value: 60
    mode: slider
    device_class: duration
    entity_category: config
    unit_of_measurement: s
    icon: mdi:timer
    step: 1
    optimistic: True
    initial_value: 5
    restore_value: True
  - platform: template
    name: "Delay OFF"
    id: DELAY_OFF
    min_value: 5
    max_value: 300
    mode: slider
    device_class: duration
    entity_category: config
    unit_of_measurement: s
    icon: mdi:timer-off
    step: 1
    optimistic: True
    initial_value: 5
    restore_value: True

switch:
  # χρειαζόμαστε 2 dry-contact relays για να δώσουμε 12v στις εισόδους της σειρήνας
  - platform: gpio
    pin: D8 # GPIO12
    # IN ενεργοποίηση σειρήνας από τον συναγερμό, εμφανίζονται 12v και ηχεί το μεγάφωνο
    name: "Alarm IN" #relay 1
  - platform: gpio
    pin: D7 # GPIO12
    # TC ενεργοποήση κατάστασης συντήρισης για 10 λεπτά όπου πρέπει να ανοίξει το καπάκι
    name: "Service Mode" #relay 2
